### ISSUE TITLE
Рефакторинг

### ISSUE THREAD

**Issue by idma88** [DreamOn-DAL/OpenIT#8]
# Класс Field

* `struct Coordinates` объявлен в приватной области в то время как экземпляр `Coordinates m_coordinates` - в публичной.
* `Coordinates m_coordinates` должен быть недоступен извне, т.е. **private**.
* Методы `GetPosX`/`GetPosY` стоило заменить на один и возвращать `struct Coordinates` (описание структуры должно быть **public**).
* Метод `GetIndex` можно перегрузить для возможности передавать `struct Coordinates`.
* Значение ячекек храниться в `int8_t`, но метод `Open` возаращает `int16_t`.
* `enum class Check` и `enum class MoveCursor` (в `player.h`) предназанчены для одного и того же - определяют ось - для поиска пустой строки/столбца или допустимого движения курсора. Реомендация: оставть только один вариант, переименовать в, например, `Axis` и вынести в общий заголовок (например, `common.h`).

# Класс Game

* `#ifndef`, определяющий Include guard, должен идти до любых объявлений и включений (`#include`).
* Метод `getWinner` неинформативен из-за сообщения "And the winner is: 0/1/2/3". Стоит сделать разбор значения и более информативные сообщения.
* Метод `playGame`:
    * Не понятно зачем экземплярам `m_playerone`/`m_playertwo` нужны направления, если они нигде не используются.
    
        Замени эти две переменные на простой массив из двух элементов. Так же можно будет использовать простой индекс на активного игрока, и легко получать доступ к экземпляру Player.
    
        Такой подход решать сразу несколько задач.
        
        Так, например, можно будет сделать проверку пустрой строки/столбца общей, без прописанных констант
        ```cpp
        if (!m_field.IsLineEmpty(m_players[m_activePlayer].GrantedDirection())) {
            ...
        }
        ```

        А так можно менять активного игрока в одном месте:
        ```cpp
        m_activePlayer = (m_activePlayer + 1) % 2;
        ```
        или универсальный вариант независящий от числа игроков
        ```cpp
        m_activePlayer = (m_activePlayer + 1) % (size_of(m_players) / m_players(Player));
        ```

    * Вызов метода `setWinner` можно оставить один - при выходе из основного цикла в случае окончания игры

    * Вместо конструкции
        ```cpp
        if (!m_field.IsLineEmpty(...)) {
            ...
        }
        ```
        лучше написать так
        ```cpp
        if (m_field.IsLineEmpty(...)) break;
        ```
        Это позволит уменьшить вложенность кода и посысит его читаемость.

    * Следующая конструкция выглядит крайне криво
        ```cpp
        uint8_t index = m_field.GetIndex(m_field.GetPosX(),m_field.GetPosY());
        if (m_field.GetField()[index] != 0) {
            m_playerone.AddScore(m_field.Open());
            flag = 1;
        }
        ```

        Метод `Open` в классе `Field` должен возвразать ноль для открытых ячеек. Таким образом можно безопасно открывать ячейку, а начислять баллы и передавать ход только в том случае, если метод `Open` вернул отличное от нуля значение.

        И ещё один эффект от такой оптимизации заключается в том, что метод `GetIndex` в классе `Field` не только не потребует перегрузки, как было описано ранее, но и вовсе может быть скрыт в **private**, т.к. всё его предназначение сводится к выполнению внутренних задач класса.

**Comment by idma88** [comment]
- Метод `Player::GetDirection` излишен.
- В методе `Game::PlayGame` никогда не произойдёт выход из цикла

**Comment by alantnv** [comment]
Прошу ознакомиться с правками.

**Comment by alantnv** [comment]
@idma88 Забыл прогнать через .clangformat, извиняюсь.
